// AUTO-GENERATED from Cloudinary. Do not edit by hand.
// Run scripts/generate-exercise-library.mjs to regenerate.

export interface ExerciseDemo {
  slug: string;       // canonical kebab-case key
  name: string;       // display name
  muscle: MuscleGroup;
  publicId: string;   // Cloudinary public_id
}

export type MuscleGroup =
  | 'abs' | 'back' | 'biceps' | 'calves' | 'cardio' | 'chest' | 'forearms' | 'legs' | 'shoulders' | 'traps' | 'triceps';

export const CLOUDINARY_CLOUD_NAME = "dl64mavdp";

/** Build the optimized streaming URL for a Cloudinary public_id. */
export function videoUrl(publicId: string): string {
  return `https://res.cloudinary.com/${CLOUDINARY_CLOUD_NAME}/video/upload/f_auto,q_auto/${publicId}.mp4`;
}

export const EXERCISE_LIBRARY: readonly ExerciseDemo[] = [
  { slug: "45-degree-bycicle-twisting-crunch", name: "45 Degree Bycicle Twisting Crunch", muscle: "abs", publicId: "45_Degree_Bycicle_Twisting_Crunch_k3ifue" },
  { slug: "45-degree-bycicle-twisting-crunch-1", name: "45 Degree Bycicle Twisting Crunch 1", muscle: "abs", publicId: "45_Degree_Bycicle_Twisting_Crunch_1_gehwvy" },
  { slug: "45-degree-side-bend", name: "45 Degree Side Bend", muscle: "abs", publicId: "45_Degree_Side_Bend_xfrik4" },
  { slug: "air-twisting-crunch", name: "Air Twisting Crunch", muscle: "abs", publicId: "Air_Twisting_Crunch_ej2fok" },
  { slug: "band-decline-sit-ups", name: "Band Decline Sit-ups", muscle: "abs", publicId: "Band_Decline_Sit-ups_fhcs17" },
  { slug: "band-side-bend", name: "Band Side Bend", muscle: "abs", publicId: "Band_Side_Bend_iwo3lk" },
  { slug: "band-standing-crunch", name: "Band Standing Crunch", muscle: "abs", publicId: "Band_Standing_Crunch_rnkj4h" },
  { slug: "band-standing-lift", name: "Band Standing Lift", muscle: "abs", publicId: "Band_Standing_Lift_e02pqr" },
  { slug: "band-twist", name: "Band Twist", muscle: "abs", publicId: "Band_Twist_rmeepy" },
  { slug: "band-twist-up-down", name: "Band Twist Up-down", muscle: "abs", publicId: "Band_Twist_Up-down_bkil8s" },
  { slug: "bench-leg-raise", name: "Bench Leg Raise", muscle: "abs", publicId: "Bench_Leg_Raise_c5ju0s" },
  { slug: "bent-knee-lying-twist", name: "Bent Knee Lying Twist", muscle: "abs", publicId: "Bent_Knee_Lying_Twist_vvvpyd" },
  { slug: "cable-kneeling-crunch", name: "Cable Kneeling Crunch", muscle: "abs", publicId: "Cable_Kneeling_Crunch_ks4i5h" },
  { slug: "cable-standing-crunch", name: "Cable Standing Crunch", muscle: "abs", publicId: "Cable_Standing_Crunch_fnr2sv" },
  { slug: "cable-standing-lift", name: "Cable Standing Lift", muscle: "abs", publicId: "Cable_Standing_Lift_u35igm" },
  { slug: "cable-twist-up-down", name: "Cable Twist up-down", muscle: "abs", publicId: "Cable_Twist_up-down_buthlv" },
  { slug: "crunch-on-bench", name: "Crunch on bench", muscle: "abs", publicId: "Crunch_on_bench_bklbpz" },
  { slug: "dumbbell-side-bend", name: "Dumbbell Side Bend", muscle: "abs", publicId: "Dumbbell_Side_Bend_ginwqy" },
  { slug: "hanging-leg-hip-raise", name: "Hanging Leg Hip Raise", muscle: "abs", publicId: "Hanging_Leg_Hip_Raise_qqnokn" },
  { slug: "hanging-straight-leg-raise", name: "Hanging Straight Leg Raise", muscle: "abs", publicId: "Hanging_Straight_Leg_Raise_yt1fla" },
  { slug: "incline-leg-hip-raise", name: "Incline Leg Hip Raise", muscle: "abs", publicId: "Incline_Leg_Hip_Raise_fpkp88" },
  { slug: "landmine-180", name: "Landmine 180", muscle: "abs", publicId: "Landmine_180_iquz2f" },
  { slug: "lever-seated-crunch", name: "Lever Seated Crunch", muscle: "abs", publicId: "Lever_Seated_Crunch_bz7jpb" },
  { slug: "lever-seated-crunch-1", name: "Lever Seated Crunch 1", muscle: "abs", publicId: "Lever_Seated_Crunch_1_tguuvw" },
  { slug: "lever-seated-leg-raise-crunch", name: "Lever Seated Leg Raise Crunch", muscle: "abs", publicId: "Lever_Seated_Leg_Raise_Crunch_btuw7b" },
  { slug: "lying-floor-leg-raise", name: "Lying Floor Leg Raise", muscle: "abs", publicId: "Lying_Floor_Leg_Raise_psrlaa" },
  { slug: "lying-straight-leg-raise", name: "Lying Straight Leg Raise", muscle: "abs", publicId: "Lying_Straight_Leg_Raise_ynnqjf" },
  { slug: "otis-ups", name: "Otis-ups", muscle: "abs", publicId: "Otis-ups_ooaaae" },
  { slug: "side-bridge-side-plank", name: "Side Bridge - Side Plank", muscle: "abs", publicId: "Side_Bridge_-_Side_Plank_m10cae" },
  { slug: "sit-up-on-exercise-ball", name: "Sit-up On Exercise Ball", muscle: "abs", publicId: "Sit-up_On_Exercise_Ball_nkjsxp" },
  { slug: "sit-ups", name: "Sit-ups", muscle: "abs", publicId: "Sit-ups_hfjlbw" },
  { slug: "spell-caster", name: "Spell Caster", muscle: "abs", publicId: "Spell_Caster_cgfvdk" },
  { slug: "stretching-chin-to-chest-stretch", name: "Stretching - Chin-to-chest Stretch", muscle: "abs", publicId: "Stretching_-_Chin-to-chest_Stretch_gvc93x" },
  { slug: "stretching-iron-cross-stretch", name: "Stretching - Iron Cross Stretch", muscle: "abs", publicId: "Stretching_-_Iron_Cross_Stretch_u3y21l" },
  { slug: "stretching-seated-twist-straight-arm", name: "Stretching - Seated Twist straight arm", muscle: "abs", publicId: "Stretching_-_Seated_Twist_straight_arm_nj2lfb" },
  { slug: "stretching-spinal-stretch-on-exercise-ball", name: "Stretching - Spinal Stretch On Exercise Ball", muscle: "abs", publicId: "Stretching_-_Spinal_Stretch_On_Exercise_Ball_dtzw8x" },
  { slug: "stretching-standing-side-bend-bent-arm", name: "Stretching - Standing Side Bend bent arm", muscle: "abs", publicId: "Stretching_-_Standing_Side_Bend_bent_arm_zrt4gy" },
  { slug: "twisting-crunch", name: "Twisting Crunch", muscle: "abs", publicId: "Twisting_Crunch_dwpgni" },
  { slug: "v-up", name: "V-up", muscle: "abs", publicId: "V-up_v2debs" },
  { slug: "vertical-leg-raise-on-parallel-bars", name: "Vertical Leg Raise on parallel bars", muscle: "abs", publicId: "Vertical_Leg_Raise_on_parallel_bars_t9pshl" },
  { slug: "weighted-leg-extension-crunch", name: "Weighted Leg Extension Crunch", muscle: "abs", publicId: "Weighted_Leg_Extension_Crunch_sscmph" },
  { slug: "45-degree-hyperextension", name: "45 Degree Hyperextension", muscle: "back", publicId: "45_Degree_Hyperextension_iknqj3" },
  { slug: "band-assisted-pull-up", name: "Band Assisted Pull-up", muscle: "back", publicId: "Band_Assisted_Pull-up_jqtxgo" },
  { slug: "band-bent-over-row", name: "Band Bent-over Row", muscle: "back", publicId: "Band_Bent-over_Row_pao6dx" },
  { slug: "band-kneeling-one-arm-pulldown", name: "Band Kneeling One Arm Pulldown", muscle: "back", publicId: "Band_Kneeling_One_Arm_Pulldown_wnwxej" },
  { slug: "band-one-arm-twisting-seated-row", name: "Band One Arm Twisting Seated Row", muscle: "back", publicId: "Band_One_Arm_Twisting_Seated_Row_nmosro" },
  { slug: "band-one-leg-kickback-bent-position", name: "Band One Leg Kickback Bent Position", muscle: "back", publicId: "Band_One_Leg_Kickback_Bent_Position_sfkq6q" },
  { slug: "band-pull-through", name: "Band Pull Through", muscle: "back", publicId: "Band_Pull_Through_pibqjg" },
  { slug: "band-seated-row", name: "Band Seated Row", muscle: "back", publicId: "Band_Seated_Row_deyo0g" },
  { slug: "band-straight-back-seated-row", name: "Band Straight Back Seated Row", muscle: "back", publicId: "Band_Straight_Back_Seated_Row_gpfp7a" },
  { slug: "barbell-bent-over-row-overgrip", name: "Barbell Bent-over Row Overgrip", muscle: "back", publicId: "Barbell_Bent-over_Row_Overgrip_fhuig6" },
  { slug: "barbell-straight-leg-deadlift", name: "Barbell Straight Leg Deadlift", muscle: "back", publicId: "Barbell_Straight_Leg_Deadlift_xiewi0" },
  { slug: "barbell-underhand-bent-over-row", name: "Barbell Underhand Bent-over Row", muscle: "back", publicId: "Barbell_Underhand_Bent-over_Row_spmahq" },
  { slug: "bench-pull-ups", name: "Bench Pull-ups", muscle: "back", publicId: "Bench_Pull-ups_csbylb" },
  { slug: "cable-bar-lateral-pulldown-reverse-grip", name: "Cable Bar Lateral Pulldown reverse-grip", muscle: "back", publicId: "Cable_Bar_Lateral_Pulldown_reverse-grip_av9yu3" },
  { slug: "cable-bar-lateral-pulldown-wide-shoulder-grip", name: "Cable Bar Lateral Pulldown wide shoulder grip", muscle: "back", publicId: "Cable_Bar_Lateral_Pulldown_wide_shoulder_grip_uvcgt9" },
  { slug: "cable-close-grip-front-lat-pulldown", name: "Cable Close Grip Front Lat Pulldown", muscle: "back", publicId: "Cable_Close_Grip_Front_Lat_Pulldown_upahwb" },
  { slug: "cable-one-arm-lateral-pulldown", name: "Cable One Arm Lateral Pulldown", muscle: "back", publicId: "Cable_One_Arm_Lateral_Pulldown_negukb" },
  { slug: "cable-one-arm-twisting-seated-row", name: "Cable One Arm Twisting Seated Row", muscle: "back", publicId: "Cable_One_Arm_Twisting_Seated_Row_grvnxa" },
  { slug: "cable-pulldown", name: "Cable Pulldown", muscle: "back", publicId: "Cable_Pulldown_eifvmm" },
  { slug: "cable-seated-high-row-v-bar", name: "Cable Seated High Row V-bar", muscle: "back", publicId: "Cable_Seated_High_Row_V-bar_om5zir" },
  { slug: "cable-seated-row-normal-grip", name: "Cable Seated Row normal grip", muscle: "back", publicId: "Cable_Seated_Row_normal_grip_fgt9gj" },
  { slug: "cable-seated-row-parallel-grip", name: "Cable Seated Row parallel grip", muscle: "back", publicId: "Cable_Seated_Row_parallel_grip_xwtpee" },
  { slug: "cable-seated-row-wide-grip", name: "Cable Seated Row wide-grip", muscle: "back", publicId: "Cable_Seated_Row_wide-grip_qz5jzz" },
  { slug: "cable-straight-arm-pulldown", name: "Cable Straight Arm Pulldown", muscle: "back", publicId: "Cable_Straight_Arm_Pulldown_elvsfa" },
  { slug: "cable-straight-back-seated-high-row-reverse-grip", name: "Cable Straight Back Seated High Row reverse-grip", muscle: "back", publicId: "Cable_Straight_Back_Seated_High_Row_reverse-grip_mjduw2" },
  { slug: "cable-straight-back-seated-row-v-grip", name: "Cable Straight Back Seated Row V-grip", muscle: "back", publicId: "Cable_Straight_Back_Seated_Row_V-grip_awohve" },
  { slug: "cambered-bar-lying-row", name: "Cambered Bar Lying Row", muscle: "back", publicId: "Cambered_Bar_Lying_Row_t3o6qt" },
  { slug: "chin-ups-pull-ups", name: "Chin-ups Pull-Ups", muscle: "back", publicId: "Chin-ups_Pull-Ups_mf8pg7" },
  { slug: "chin-ups-narrow-parallel-grip", name: "Chin-ups narrow parallel grip", muscle: "back", publicId: "Chin-ups_narrow_parallel_grip_mohrpy" },
  { slug: "close-grip-chin-up", name: "Close Grip Chin-up", muscle: "back", publicId: "Close_Grip_Chin-up_nyp9zo" },
  { slug: "commando-pull-up", name: "Commando Pull-up", muscle: "back", publicId: "Commando_Pull-up_c2hd68" },
  { slug: "dumbbell-bent-over-row", name: "Dumbbell Bent-over Row", muscle: "back", publicId: "Dumbbell_Bent-over_Row_fplrll" },
  { slug: "dumbbell-deadlift", name: "Dumbbell Deadlift", muscle: "back", publicId: "Dumbbell_Deadlift_gt14t3" },
  { slug: "dumbbell-hammer-grip-incline-bench-row", name: "Dumbbell Hammer Grip Incline Bench Row", muscle: "back", publicId: "Dumbbell_Hammer_Grip_Incline_Bench_Row_yqeat8" },
  { slug: "dumbbell-incline-row", name: "Dumbbell Incline Row", muscle: "back", publicId: "Dumbbell_Incline_Row_tiem5f" },
  { slug: "dumbbell-lying-rear-delt-row", name: "Dumbbell Lying Rear Delt Row", muscle: "back", publicId: "Dumbbell_Lying_Rear_Delt_Row_pcftft" },
  { slug: "dumbbell-palm-rotational-bent-over-row", name: "Dumbbell Palm Rotational Bent Over Row", muscle: "back", publicId: "Dumbbell_Palm_Rotational_Bent_Over_Row_c8vatu" },
  { slug: "dumbbell-reverse-grip-row", name: "Dumbbell Reverse Grip Row", muscle: "back", publicId: "Dumbbell_Reverse_Grip_Row_kscsfl" },
  { slug: "dumbbell-stiff-leg-deadlift", name: "Dumbbell Stiff Leg Deadlift", muscle: "back", publicId: "Dumbbell_Stiff_Leg_Deadlift_l7lyot" },
  { slug: "hammer-grip-pull-up", name: "Hammer Grip Pull-up", muscle: "back", publicId: "Hammer_Grip_Pull-up_grikwm" },
  { slug: "inverted-row-between-chairs", name: "Inverted Row Between Chairs", muscle: "back", publicId: "Inverted_Row_Between_Chairs_jzacle" },
  { slug: "inverted-row-with-straps", name: "Inverted Row With Straps", muscle: "back", publicId: "Inverted_Row_With_Straps_rp9ibj" },
  { slug: "kettlebell-deadlift", name: "Kettlebell Deadlift", muscle: "back", publicId: "Kettlebell_Deadlift_keqa9e" },
  { slug: "lever-back-extension", name: "Lever Back Extension", muscle: "back", publicId: "Lever_Back_Extension_mru6oz" },
  { slug: "lever-high-row", name: "Lever High Row", muscle: "back", publicId: "Lever_High_Row_kjhc7r" },
  { slug: "lever-reverse-hyperextension", name: "Lever Reverse Hyperextension", muscle: "back", publicId: "Lever_Reverse_Hyperextension_erhy6b" },
  { slug: "lever-reverse-t-bar-row", name: "Lever Reverse T-Bar Row", muscle: "back", publicId: "Lever_Reverse_T-Bar_Row_gn74z6" },
  { slug: "lever-t-bar-row", name: "Lever T-bar Row", muscle: "back", publicId: "Lever_T-bar_Row_hxlcth" },
  { slug: "pull-up-shoulder-grip", name: "Pull-up shoulder grip", muscle: "back", publicId: "Pull-up_shoulder_grip_gwndfw" },
  { slug: "pull-up-wide-back-grip", name: "Pull-up wide back grip", muscle: "back", publicId: "Pull-up_wide_back_grip_awgxxy" },
  { slug: "pull-up-wide-front-grip", name: "Pull-up wide front grip", muscle: "back", publicId: "Pull-up_wide_front_grip_mydp0b" },
  { slug: "reverse-grip-machine-lat-pulldown", name: "Reverse Grip Machine Lat Pulldown", muscle: "back", publicId: "Reverse_Grip_Machine_Lat_Pulldown_iql2jz" },
  { slug: "reverse-grip-pull-up", name: "Reverse Grip Pull-up", muscle: "back", publicId: "Reverse_Grip_Pull-up_lgznuw" },
  { slug: "ring-high-row", name: "Ring High Row", muscle: "back", publicId: "Ring_High_Row_w4ecok" },
  { slug: "single-dumbbell-stiff-leg-deadlift", name: "Single Dumbbell Stiff Leg Deadlift", muscle: "back", publicId: "Single_Dumbbell_Stiff_Leg_Deadlift_uno6zw" },
  { slug: "smith-deadlift-deadlift", name: "Smith Deadlift - Deadlift", muscle: "back", publicId: "Smith_Deadlift_-_Deadlift_xfiy8s" },
  { slug: "smith-deadlift-deadlift-1", name: "Smith Deadlift - Deadlift 1", muscle: "back", publicId: "Smith_Deadlift_-_Deadlift_1_pbf7pi" },
  { slug: "stretching-dynamic-back-stretch", name: "Stretching - Dynamic Back Stretch", muscle: "back", publicId: "Stretching_-_Dynamic_Back_Stretch_zamci4" },
  { slug: "stretching-elbows-back-stretch", name: "Stretching - Elbows Back Stretch", muscle: "back", publicId: "Stretching_-_Elbows_Back_Stretch_j28y2f" },
  { slug: "stretching-kneeling-lat-stretch", name: "Stretching - Kneeling Lat Stretch", muscle: "back", publicId: "Stretching_-_Kneeling_Lat_Stretch_ieeew7" },
  { slug: "stretching-middle-back-stretch", name: "Stretching - Middle Back Stretch", muscle: "back", publicId: "Stretching_-_Middle_Back_Stretch_orzop6" },
  { slug: "stretching-middle-back-stretch-1", name: "Stretching - Middle Back Stretch 1", muscle: "back", publicId: "Stretching_-_Middle_Back_Stretch_1_zbwoa8" },
  { slug: "stretching-seated-lower-back-stretch", name: "Stretching - Seated Lower Back Stretch", muscle: "back", publicId: "Stretching_-_Seated_Lower_Back_Stretch_anrjdx" },
  { slug: "stretching-seated-wide-angle-pose-sequence", name: "Stretching - Seated Wide Angle Pose Sequence", muscle: "back", publicId: "Stretching_-_Seated_Wide_Angle_Pose_Sequence_uiztwi" },
  { slug: "stretching-sitting-bent-over-back-stretch", name: "Stretching - Sitting Bent Over Back Stretch", muscle: "back", publicId: "Stretching_-_Sitting_Bent_Over_Back_Stretch_isk84k" },
  { slug: "stretching-slopes-towards-stretch", name: "Stretching - Slopes Towards Stretch", muscle: "back", publicId: "Stretching_-_Slopes_Towards_Stretch_semqzv" },
  { slug: "stretching-spine-stretch", name: "Stretching - Spine Stretch", muscle: "back", publicId: "Stretching_-_Spine_Stretch_ne0jha" },
  { slug: "stretching-spine-stretch-forward", name: "Stretching - Spine Stretch Forward", muscle: "back", publicId: "Stretching_-_Spine_Stretch_Forward_n0pkva" },
  { slug: "stretching-standing-back-rotation-stretch", name: "Stretching - Standing Back Rotation Stretch", muscle: "back", publicId: "Stretching_-_Standing_Back_Rotation_Stretch_bvzyp8" },
  { slug: "stretching-standing-lateral-stretch", name: "Stretching - Standing Lateral Stretch", muscle: "back", publicId: "Stretching_-_Standing_Lateral_Stretch_kowygt" },
  { slug: "stretching-standing-lateral-stretch-1", name: "Stretching - Standing Lateral Stretch 1", muscle: "back", publicId: "Stretching_-_Standing_Lateral_Stretch_1_jtwmqy" },
  { slug: "barbell-curl", name: "Barbell Curl", muscle: "biceps", publicId: "Barbell_Curl_lqhiqh" },
  { slug: "barbell-drag-curl", name: "Barbell Drag Curl", muscle: "biceps", publicId: "Barbell_Drag_Curl_r8eqzo" },
  { slug: "barbell-prone-incline-curl", name: "Barbell Prone Incline Curl", muscle: "biceps", publicId: "Barbell_Prone_Incline_Curl_vf9qot" },
  { slug: "cable-one-arm-curl", name: "Cable One Arm Curl", muscle: "biceps", publicId: "Cable_One_Arm_Curl_b0jy1z" },
  { slug: "cable-standing-inner-curl", name: "Cable Standing Inner Curl", muscle: "biceps", publicId: "Cable_Standing_Inner_Curl_moez5g" },
  { slug: "dumbbell-alternate-biceps-curl", name: "Dumbbell Alternate Biceps Curl", muscle: "biceps", publicId: "Dumbbell_Alternate_Biceps_Curl_becxee" },
  { slug: "dumbbell-alternate-seated-biceps-curl", name: "Dumbbell Alternate Seated Biceps Curl", muscle: "biceps", publicId: "Dumbbell_Alternate_Seated_Biceps_Curl_am50ka" },
  { slug: "dumbbell-biceps-curl", name: "Dumbbell Biceps Curl", muscle: "biceps", publicId: "Dumbbell_Biceps_Curl_kfguki" },
  { slug: "dumbbell-concentration-curl", name: "Dumbbell Concentration Curl", muscle: "biceps", publicId: "Dumbbell_Concentration_Curl_gyuujt" },
  { slug: "dumbbell-cross-body-hammer-curl", name: "Dumbbell Cross Body Hammer Curl", muscle: "biceps", publicId: "Dumbbell_Cross_Body_Hammer_Curl_m2rzbi" },
  { slug: "dumbbell-incline-biceps-curl", name: "Dumbbell Incline Biceps Curl", muscle: "biceps", publicId: "Dumbbell_Incline_Biceps_Curl_maagmj" },
  { slug: "dumbbell-incline-curl", name: "Dumbbell Incline Curl", muscle: "biceps", publicId: "Dumbbell_Incline_Curl_ay9oxm" },
  { slug: "dumbbell-incline-hammer-curl", name: "Dumbbell Incline Hammer Curl", muscle: "biceps", publicId: "Dumbbell_Incline_Hammer_Curl_gi0kas" },
  { slug: "dumbbell-one-arm-zottman-preacher-curl", name: "Dumbbell One Arm Zottman Preacher Curl", muscle: "biceps", publicId: "Dumbbell_One_Arm_Zottman_Preacher_Curl_neygsk" },
  { slug: "dumbbell-preacher-curl-over-exercise-ball", name: "Dumbbell Preacher Curl Over Exercise Ball", muscle: "biceps", publicId: "Dumbbell_Preacher_Curl_Over_Exercise_Ball_wopgcz" },
  { slug: "dumbbell-prone-incline-curl", name: "Dumbbell Prone Incline Curl", muscle: "biceps", publicId: "Dumbbell_Prone_Incline_Curl_uve7xs" },
  { slug: "dumbbell-seated-preacher-curl", name: "Dumbbell Seated Preacher Curl", muscle: "biceps", publicId: "Dumbbell_Seated_Preacher_Curl_jndlcg" },
  { slug: "ez-barbell-biceps-curl", name: "EZ Barbell Biceps Curl", muscle: "biceps", publicId: "EZ_Barbell_Biceps_Curl_h66l7d" },
  { slug: "lever-preacher-curl", name: "Lever Preacher Curl", muscle: "biceps", publicId: "Lever_Preacher_Curl_bygg2x" },
  { slug: "lying-supine-dumbbell-curl", name: "Lying Supine Dumbbell Curl", muscle: "biceps", publicId: "Lying_Supine_Dumbbell_Curl_uttvfn" },
  { slug: "stretching-butterfly-yoga-pose", name: "Stretching - Butterfly Yoga Pose", muscle: "biceps", publicId: "Stretching_-_Butterfly_Yoga_Pose_r8wr92" },
  { slug: "band-standing-calf-raise", name: "Band Standing Calf Raise", muscle: "calves", publicId: "Band_Standing_Calf_Raise_bmwcff" },
  { slug: "donkey-calf-raise", name: "Donkey Calf Raise", muscle: "calves", publicId: "Donkey_Calf_Raise_qwtysx" },
  { slug: "dumbbell-seated-calf-raise", name: "Dumbbell Seated Calf Raise", muscle: "calves", publicId: "Dumbbell_Seated_Calf_Raise_bmhv9q" },
  { slug: "dumbbell-single-leg-calf-raise", name: "Dumbbell Single Leg Calf Raise", muscle: "calves", publicId: "Dumbbell_Single_Leg_Calf_Raise_gknpvm" },
  { slug: "dumbbell-standing-calf-raise", name: "Dumbbell Standing Calf Raise", muscle: "calves", publicId: "Dumbbell_Standing_Calf_Raise_nr8ni5" },
  { slug: "lever-seated-calf-raise", name: "Lever Seated Calf Raise", muscle: "calves", publicId: "Lever_Seated_Calf_Raise_gpzszv" },
  { slug: "lever-standing-calf-raise", name: "Lever Standing Calf Raise", muscle: "calves", publicId: "Lever_Standing_Calf_Raise_do6skk" },
  { slug: "sled-45-degree-calf-press", name: "Sled 45 Degree Calf Press", muscle: "calves", publicId: "Sled_45_Degree_Calf_Press_qwum7f" },
  { slug: "smith-calf-raise", name: "Smith Calf Raise", muscle: "calves", publicId: "Smith_Calf_Raise_irt7iz" },
  { slug: "stretching-calf-stretch-with-rope", name: "Stretching - Calf Stretch with Rope", muscle: "calves", publicId: "Stretching_-_Calf_Stretch_with_Rope_xw3v6h" },
  { slug: "stretching-calf-stretch-with-strap", name: "Stretching - Calf Stretch with Strap", muscle: "calves", publicId: "Stretching_-_Calf_Stretch_with_Strap_tawynp" },
  { slug: "stretching-circles-knee-stretch", name: "Stretching - Circles Knee Stretch", muscle: "calves", publicId: "Stretching_-_Circles_Knee_Stretch_nvy9wn" },
  { slug: "stretching-feet-and-ankles-rotation-stretch", name: "Stretching - Feet and Ankles Rotation Stretch", muscle: "calves", publicId: "Stretching_-_Feet_and_Ankles_Rotation_Stretch_zkewff" },
  { slug: "stretching-feet-and-ankles-stretch", name: "Stretching - Feet and Ankles Stretch", muscle: "calves", publicId: "Stretching_-_Feet_and_Ankles_Stretch_ivghbl" },
  { slug: "stretching-peroneals-stretch", name: "Stretching - Peroneals Stretch", muscle: "calves", publicId: "Stretching_-_Peroneals_Stretch_ztofuw" },
  { slug: "stretching-seated-calf-stretch", name: "Stretching - Seated Calf Stretch", muscle: "calves", publicId: "Stretching_-_Seated_Calf_Stretch_dcfoza" },
  { slug: "stretching-stairs-calf-stretch", name: "Stretching - Stairs Calf Stretch", muscle: "calves", publicId: "Stretching_-_Stairs_Calf_Stretch_iakyw9" },
  { slug: "stretching-standing-bench-calf-stretch", name: "Stretching - Standing Bench Calf Stretch", muscle: "calves", publicId: "Stretching_-_Standing_Bench_Calf_Stretch_mgwuw7" },
  { slug: "battling-ropes", name: "Battling Ropes", muscle: "cardio", publicId: "Battling_Ropes_ng8vle" },
  { slug: "burpee", name: "Burpee", muscle: "cardio", publicId: "Burpee_oh2cbc" },
  { slug: "cardio-exercises", name: "Cardio Exercises", muscle: "cardio", publicId: "Cardio_Exercises_eko8kw" },
  { slug: "cardio-exercises-machines", name: "Cardio Exercises Machines", muscle: "cardio", publicId: "Cardio_Exercises_Machines_v6wpmo" },
  { slug: "elliptical", name: "Elliptical", muscle: "cardio", publicId: "Elliptical_n3ckjt" },
  { slug: "jump-rope", name: "Jump Rope", muscle: "cardio", publicId: "Jump_Rope_d2as5n" },
  { slug: "jump-step-up", name: "Jump Step-up", muscle: "cardio", publicId: "Jump_Step-up_b9pn4c" },
  { slug: "jumping-jack", name: "Jumping Jack", muscle: "cardio", publicId: "Jumping_Jack_uhzmt8" },
  { slug: "running", name: "Running", muscle: "cardio", publicId: "Running_sravkq" },
  { slug: "stationary-bike", name: "Stationary Bike", muscle: "cardio", publicId: "Stationary_Bike_mnku3x" },
  { slug: "stretching-bridge-pose-setu-bandhasana", name: "Stretching - Bridge Pose Setu Bandhasana", muscle: "cardio", publicId: "Stretching_-_Bridge_Pose_Setu_Bandhasana_nnst0y" },
  { slug: "stretching-bridge-pose-setu-bandhasana-1", name: "Stretching - Bridge Pose Setu Bandhasana 1", muscle: "cardio", publicId: "Stretching_-_Bridge_Pose_Setu_Bandhasana_1_bikryv" },
  { slug: "stretching-flexion-leg-sit-up", name: "Stretching - Flexion Leg Sit-up", muscle: "cardio", publicId: "Stretching_-_Flexion_Leg_Sit-up_ydsyqt" },
  { slug: "stretching-front-toe-touch", name: "Stretching - Front Toe Touch", muscle: "cardio", publicId: "Stretching_-_Front_Toe_Touch_wwjnic" },
  { slug: "stretching-plyo-side-lunge-stretch", name: "Stretching - Plyo Side Lunge Stretch", muscle: "cardio", publicId: "Stretching_-_Plyo_Side_Lunge_Stretch_vnmlgv" },
  { slug: "stretching-single-leg-stretch-bent-knee", name: "Stretching - Single Leg Stretch bent knee", muscle: "cardio", publicId: "Stretching_-_Single_Leg_Stretch_bent_knee_pvajct" },
  { slug: "stretching-single-straight-leg-stretch", name: "Stretching - Single Straight Leg Stretch", muscle: "cardio", publicId: "Stretching_-_Single_Straight_Leg_Stretch_ddibyc" },
  { slug: "treadmill-running", name: "Treadmill Running", muscle: "cardio", publicId: "Treadmill_Running_cjpqnj" },
  { slug: "walk-wave-machine", name: "Walk Wave Machine", muscle: "cardio", publicId: "Walk_Wave_Machine_pe5ovz" },
  { slug: "band-high-fly", name: "Band High Fly", muscle: "chest", publicId: "Band_High_Fly_zxd8bg" },
  { slug: "barbell-bench-press", name: "Barbell Bench Press", muscle: "chest", publicId: "Barbell_Bench_Press_ueygrl" },
  { slug: "barbell-decline-bench-press", name: "Barbell Decline Bench Press", muscle: "chest", publicId: "Barbell_Decline_Bench_Press_grqru4" },
  { slug: "barbell-incline-bench-press", name: "Barbell Incline Bench Press", muscle: "chest", publicId: "Barbell_Incline_Bench_Press_w9v1ep" },
  { slug: "cable-lying-fly-flat-bench-cable-fly", name: "Cable Lying Fly Flat Bench Cable Fly", muscle: "chest", publicId: "Cable_Lying_Fly_Flat_Bench_Cable_Fly_nypx5e" },
  { slug: "cable-standing-fly-crossover-fly", name: "Cable Standing Fly Crossover fly", muscle: "chest", publicId: "Cable_Standing_Fly_Crossover_fly_deka2k" },
  { slug: "chest-dips", name: "Chest Dips", muscle: "chest", publicId: "Chest_Dips_ofi4du" },
  { slug: "decline-dumbbell-bench-press-45-degree", name: "Decline Dumbbell Bench Press 45 degree", muscle: "chest", publicId: "Decline_Dumbbell_Bench_Press_45_degree_efeswl" },
  { slug: "deep-push-ups", name: "Deep Push-ups", muscle: "chest", publicId: "Deep_Push-ups_aumq0r" },
  { slug: "dumbbell-bench-press", name: "Dumbbell Bench Press", muscle: "chest", publicId: "Dumbbell_Bench_Press_kytmri" },
  { slug: "dumbbell-decline-fly-45-degree", name: "Dumbbell Decline Fly 45 degree", muscle: "chest", publicId: "Dumbbell_Decline_Fly_45_degree_ebhykv" },
  { slug: "dumbbell-decline-fly-45-degree-1", name: "Dumbbell Decline Fly 45 degree 1", muscle: "chest", publicId: "Dumbbell_Decline_Fly_45_degree_1_x12yga" },
  { slug: "dumbbell-fly", name: "Dumbbell Fly", muscle: "chest", publicId: "Dumbbell_Fly_t2xknl" },
  { slug: "dumbbell-fly-on-exercise-ball", name: "Dumbbell Fly On Exercise Ball", muscle: "chest", publicId: "Dumbbell_Fly_On_Exercise_Ball_h63j5q" },
  { slug: "dumbbell-incline-bench-press", name: "Dumbbell Incline Bench Press", muscle: "chest", publicId: "Dumbbell_Incline_Bench_Press_edrruu" },
  { slug: "dumbbell-incline-fly", name: "Dumbbell Incline Fly", muscle: "chest", publicId: "Dumbbell_Incline_Fly_willm8" },
  { slug: "dumbbell-incline-fly-on-exercise-ball", name: "Dumbbell Incline Fly On Exercise Ball", muscle: "chest", publicId: "Dumbbell_Incline_Fly_On_Exercise_Ball_wmdyb5" },
  { slug: "dumbbell-lying-hammer-press", name: "Dumbbell Lying Hammer Press", muscle: "chest", publicId: "Dumbbell_Lying_Hammer_Press_ebfvpk" },
  { slug: "incline-push-ups", name: "Incline Push-Ups", muscle: "chest", publicId: "Incline_Push-Ups_enu7n7" },
  { slug: "lever-chest-press", name: "Lever Chest Press", muscle: "chest", publicId: "Lever_Chest_Press_xii7ja" },
  { slug: "lever-incline-hammer-chest-press", name: "Lever Incline Hammer Chest Press", muscle: "chest", publicId: "Lever_Incline_Hammer_Chest_Press_yc0acz" },
  { slug: "lever-lying-chest-press", name: "Lever Lying Chest Press", muscle: "chest", publicId: "Lever_Lying_Chest_Press_evhyj8" },
  { slug: "lever-pec-deck-fly", name: "Lever Pec Deck Fly", muscle: "chest", publicId: "Lever_Pec_Deck_Fly_ejquci" },
  { slug: "push-ups", name: "Push-ups", muscle: "chest", publicId: "Push-ups_wi3rwb" },
  { slug: "stretching-above-head-chest-stretch", name: "Stretching - Above Head Chest Stretch", muscle: "chest", publicId: "Stretching_-_Above_Head_Chest_Stretch_tediov" },
  { slug: "stretching-back-pec-stretch", name: "Stretching - Back Pec Stretch", muscle: "chest", publicId: "Stretching_-_Back_Pec_Stretch_lwg0x6" },
  { slug: "stretching-dynamic-chest-stretch", name: "Stretching - Dynamic Chest Stretch", muscle: "chest", publicId: "Stretching_-_Dynamic_Chest_Stretch_ueq4nd" },
  { slug: "stretching-kneeling-back-rotation-stretch", name: "Stretching - Kneeling Back Rotation Stretch", muscle: "chest", publicId: "Stretching_-_Kneeling_Back_Rotation_Stretch_twapsz" },
  { slug: "stretching-standing-reach-up-back-rotation-stretch", name: "Stretching - Standing Reach Up Back Rotation Stretch", muscle: "chest", publicId: "Stretching_-_Standing_Reach_Up_Back_Rotation_Stretch_gnxgfw" },
  { slug: "stretching-standing-wheel-rollout", name: "Stretching - Standing Wheel Rollout", muscle: "chest", publicId: "Stretching_-_Standing_Wheel_Rollout_uexvcw" },
  { slug: "triceps-dips", name: "Triceps Dips", muscle: "chest", publicId: "Triceps_Dips_lr7bas" },
  { slug: "wide-grip-push-ups", name: "Wide Grip Push-ups", muscle: "chest", publicId: "Wide_Grip_Push-ups_iqlbgm" },
  { slug: "barbell-reverse-wrist-curl-over-grip", name: "Barbell Reverse Wrist Curl over-grip", muscle: "forearms", publicId: "Barbell_Reverse_Wrist_Curl_over-grip_d6qg6g" },
  { slug: "barbell-standing-back-wrist-curl", name: "Barbell Standing Back Wrist Curl", muscle: "forearms", publicId: "Barbell_Standing_Back_Wrist_Curl_ckykbh" },
  { slug: "dumbbell-behind-back-wrist-curl", name: "Dumbbell Behind Back Wrist Curl", muscle: "forearms", publicId: "Dumbbell_Behind_Back_Wrist_Curl_y72cwl" },
  { slug: "dumbbell-over-bench-wrist-curl", name: "Dumbbell Over Bench Wrist Curl", muscle: "forearms", publicId: "Dumbbell_Over_Bench_Wrist_Curl_gor8ef" },
  { slug: "dumbbell-seated-neutral-wrist-curl", name: "Dumbbell Seated Neutral Wrist Curl", muscle: "forearms", publicId: "Dumbbell_Seated_Neutral_Wrist_Curl_mxdr5p" },
  { slug: "stretching-side-wrist-pull-stretch", name: "Stretching - Side Wrist Pull Stretch", muscle: "forearms", publicId: "Stretching_-_Side_Wrist_Pull_Stretch_pxs90b" },
  { slug: "stretching-wrist-circles", name: "Stretching - Wrist Circles", muscle: "forearms", publicId: "Stretching_-_Wrist_Circles_uexpuc" },
  { slug: "weighted-standing-curl", name: "Weighted Standing Curl", muscle: "forearms", publicId: "Weighted_Standing_Curl_hjg9j5" },
  { slug: "band-bent-over-hip-extension", name: "Band Bent Over Hip Extension", muscle: "legs", publicId: "Band_Bent_Over_Hip_Extension_p6pghb" },
  { slug: "band-hip-abduction", name: "Band Hip Abduction", muscle: "legs", publicId: "Band_Hip_Abduction_s3qzv2" },
  { slug: "band-hip-adduction", name: "Band Hip Adduction", muscle: "legs", publicId: "Band_Hip_Adduction_nn35cc" },
  { slug: "band-leg-curl", name: "Band Leg Curl", muscle: "legs", publicId: "Band_Leg_Curl_cjdh4d" },
  { slug: "band-seated-leg-extension", name: "Band Seated Leg Extension", muscle: "legs", publicId: "Band_Seated_Leg_Extension_dfzwx4" },
  { slug: "band-standing-hip-extension", name: "Band Standing Hip Extension", muscle: "legs", publicId: "Band_Standing_Hip_Extension_ckbhnn" },
  { slug: "band-standing-leg-curl", name: "Band Standing Leg Curl", muscle: "legs", publicId: "Band_Standing_Leg_Curl_dbbdqt" },
  { slug: "barbell-clean-and-press", name: "Barbell Clean And Press", muscle: "legs", publicId: "Barbell_Clean_And_Press_l9jh7o" },
  { slug: "barbell-front-chest-squat", name: "Barbell Front Chest Squat", muscle: "legs", publicId: "Barbell_Front_Chest_Squat_uew7bg" },
  { slug: "barbell-lunge", name: "Barbell Lunge", muscle: "legs", publicId: "Barbell_Lunge_wdygrq" },
  { slug: "classic-barbell-squat", name: "Classic Barbell Squat", muscle: "legs", publicId: "Classic_Barbell_Squat_cdm0vf" },
  { slug: "close-feet-leg-press", name: "Close Feet Leg Press", muscle: "legs", publicId: "Close_Feet_Leg_Press_n9cquy" },
  { slug: "dumbbell-bar-grip-sumo-squat", name: "Dumbbell Bar Grip Sumo Squat", muscle: "legs", publicId: "Dumbbell_Bar_Grip_Sumo_Squat_tlydu3" },
  { slug: "dumbbell-front-squat", name: "Dumbbell Front Squat", muscle: "legs", publicId: "Dumbbell_Front_Squat_w8h2ei" },
  { slug: "dumbbell-goblet-squat", name: "Dumbbell Goblet Squat", muscle: "legs", publicId: "Dumbbell_Goblet_Squat_t84p4s" },
  { slug: "dumbbell-lunge", name: "Dumbbell Lunge", muscle: "legs", publicId: "Dumbbell_Lunge_wrmyuz" },
  { slug: "dumbbell-lying-femoral", name: "Dumbbell Lying Femoral", muscle: "legs", publicId: "Dumbbell_Lying_Femoral_riklnm" },
  { slug: "dumbbell-single-leg-squat", name: "Dumbbell Single Leg Squat", muscle: "legs", publicId: "Dumbbell_Single_Leg_Squat_jhvdv5" },
  { slug: "dumbbell-squat", name: "Dumbbell Squat", muscle: "legs", publicId: "Dumbbell_Squat_emgnhp" },
  { slug: "lever-horizontal-leg-press", name: "Lever Horizontal Leg Press", muscle: "legs", publicId: "Lever_Horizontal_Leg_Press_oyslcm" },
  { slug: "lever-kneeling-leg-curl", name: "Lever Kneeling Leg Curl", muscle: "legs", publicId: "Lever_Kneeling_Leg_Curl_iugo5n" },
  { slug: "lever-leg-extension", name: "Lever Leg Extension", muscle: "legs", publicId: "Lever_Leg_Extension_mlkhnx" },
  { slug: "lever-lying-leg-curl", name: "Lever Lying Leg Curl", muscle: "legs", publicId: "Lever_Lying_Leg_Curl_jg5877" },
  { slug: "lever-seated-hip-abduction", name: "Lever Seated Hip Abduction", muscle: "legs", publicId: "Lever_Seated_Hip_Abduction_ql81zq" },
  { slug: "lever-seated-hip-adduction", name: "Lever Seated Hip Adduction", muscle: "legs", publicId: "Lever_Seated_Hip_Adduction_tew3gw" },
  { slug: "lever-seated-leg-curl", name: "Lever Seated Leg Curl", muscle: "legs", publicId: "Lever_Seated_Leg_Curl_uxdqbd" },
  { slug: "lever-standing-hip-extension", name: "Lever Standing Hip Extension", muscle: "legs", publicId: "Lever_Standing_Hip_Extension_twkgx6" },
  { slug: "lever-standing-rear-kick", name: "Lever Standing Rear Kick", muscle: "legs", publicId: "Lever_Standing_Rear_Kick_mhghjx" },
  { slug: "rear-decline-bridge", name: "Rear Decline Bridge", muscle: "legs", publicId: "Rear_Decline_Bridge_k2bvgh" },
  { slug: "sled-45-degree-leg-wide-press", name: "Sled 45 Degree Leg Wide Press", muscle: "legs", publicId: "Sled_45_Degree_Leg_Wide_Press_vav4bu" },
  { slug: "sled-hack-squat", name: "Sled Hack Squat", muscle: "legs", publicId: "Sled_Hack_Squat_wjohne" },
  { slug: "smith-chair-squat", name: "Smith Chair Squat", muscle: "legs", publicId: "Smith_Chair_Squat_zmtcej" },
  { slug: "smith-leg-press", name: "Smith Leg Press", muscle: "legs", publicId: "Smith_Leg_Press_mhn0ve" },
  { slug: "squat", name: "Squat", muscle: "legs", publicId: "Squat_w8clss" },
  { slug: "stretching-adductor-stretch", name: "Stretching - Adductor stretch", muscle: "legs", publicId: "Stretching_-_Adductor_stretch_clfds9" },
  { slug: "stretching-all-fours-squad-stretch", name: "Stretching - All Fours Squad Stretch", muscle: "legs", publicId: "Stretching_-_All_Fours_Squad_Stretch_aurlam" },
  { slug: "stretching-boat-stretch", name: "Stretching - Boat Stretch", muscle: "legs", publicId: "Stretching_-_Boat_Stretch_snskda" },
  { slug: "stretching-ceiling-look-stretch", name: "Stretching - Ceiling Look Stretch", muscle: "legs", publicId: "Stretching_-_Ceiling_Look_Stretch_zx3yod" },
  { slug: "stretching-crossover-kneeling-hip-flexor-stretch", name: "Stretching - Crossover Kneeling Hip Flexor Stretch", muscle: "legs", publicId: "Stretching_-_Crossover_Kneeling_Hip_Flexor_Stretch_zslhvr" },
  { slug: "stretching-hamstring-stretch", name: "Stretching - Hamstring Stretch", muscle: "legs", publicId: "Stretching_-_Hamstring_Stretch_tl3nob" },
  { slug: "stretching-hip-circles-stretch", name: "Stretching - Hip Circles Stretch", muscle: "legs", publicId: "Stretching_-_Hip_Circles_Stretch_tsfpm4" },
  { slug: "stretching-hip-extension-stretch", name: "Stretching - Hip Extension Stretch", muscle: "legs", publicId: "Stretching_-_Hip_Extension_Stretch_vnrxbh" },
  { slug: "stretching-hip-flexor-stretch-rear-foot-elevated", name: "Stretching - Hip Flexor Stretch Rear foot elevated", muscle: "legs", publicId: "Stretching_-_Hip_Flexor_Stretch_Rear_foot_elevated_e0ipim" },
  { slug: "stretching-hip-flexor-and-quad-stretch", name: "Stretching - Hip Flexor and Quad Stretch", muscle: "legs", publicId: "Stretching_-_Hip_Flexor_and_Quad_Stretch_wnj0ca" },
  { slug: "stretching-knee-raise", name: "Stretching - Knee Raise", muscle: "legs", publicId: "Stretching_-_Knee_Raise_y3rr0c" },
  { slug: "stretching-quadriceps-lying-stretch", name: "Stretching - Quadriceps lying stretch", muscle: "legs", publicId: "Stretching_-_Quadriceps_lying_stretch_px6gaw" },
  { slug: "stretching-quadriceps-stretch", name: "Stretching - Quadriceps stretch", muscle: "legs", publicId: "Stretching_-_Quadriceps_stretch_hxjd8v" },
  { slug: "stretching-runners-stretch", name: "Stretching - Runners Stretch", muscle: "legs", publicId: "Stretching_-_Runners_Stretch_mixrqn" },
  { slug: "weighted-sissy-squat", name: "Weighted Sissy Squat", muscle: "legs", publicId: "Weighted_Sissy_Squat_himsnp" },
  { slug: "band-bent-over-rear-lateral-raise", name: "Band Bent-over Rear Lateral Raise", muscle: "shoulders", publicId: "Band_Bent-over_Rear_Lateral_Raise_dgzsnj" },
  { slug: "band-one-arm-forward-raise", name: "Band One Arm Forward Raise", muscle: "shoulders", publicId: "Band_One_Arm_Forward_Raise_ew8wpp" },
  { slug: "band-standing-rear-delt-row", name: "Band Standing Rear Delt Row", muscle: "shoulders", publicId: "Band_Standing_Rear_Delt_Row_brdcns" },
  { slug: "barbell-front-raise", name: "Barbell Front Raise", muscle: "shoulders", publicId: "Barbell_Front_Raise_wti6h0" },
  { slug: "barbell-seated-behind-head-military-press", name: "Barbell Seated Behind Head Military Press", muscle: "shoulders", publicId: "Barbell_Seated_Behind_Head_Military_Press_ca9jnb" },
  { slug: "barbell-upright-row-wide-grip", name: "Barbell Upright Row wide-grip", muscle: "shoulders", publicId: "Barbell_Upright_Row_wide-grip_rxqk81" },
  { slug: "cable-crossover-reverse-fly", name: "Cable Crossover Reverse Fly", muscle: "shoulders", publicId: "Cable_Crossover_Reverse_Fly_xj23jf" },
  { slug: "cable-front-raise", name: "Cable Front Raise", muscle: "shoulders", publicId: "Cable_Front_Raise_xhtmsq" },
  { slug: "cable-lateral-raise", name: "Cable Lateral Raise", muscle: "shoulders", publicId: "Cable_Lateral_Raise_bpegmw" },
  { slug: "cable-one-arm-forward-raise", name: "Cable One Arm Forward Raise", muscle: "shoulders", publicId: "Cable_One_Arm_Forward_Raise_i2s9tl" },
  { slug: "cable-one-arm-lateral-raise", name: "Cable One Arm Lateral Raise", muscle: "shoulders", publicId: "Cable_One_Arm_Lateral_Raise_judlaq" },
  { slug: "cable-rear-delt-row-with-rope", name: "Cable Rear Delt Row with rope", muscle: "shoulders", publicId: "Cable_Rear_Delt_Row_with_rope_uvqvcc" },
  { slug: "dumbbell-alternate-shoulder-press", name: "Dumbbell Alternate Shoulder Press", muscle: "shoulders", publicId: "Dumbbell_Alternate_Shoulder_Press_t1mzxw" },
  { slug: "dumbbell-arnold-press", name: "Dumbbell Arnold Press", muscle: "shoulders", publicId: "Dumbbell_Arnold_Press_p5miy8" },
  { slug: "dumbbell-bench-seated-press", name: "Dumbbell Bench Seated Press", muscle: "shoulders", publicId: "Dumbbell_Bench_Seated_Press_hqzugx" },
  { slug: "dumbbell-front-raise", name: "Dumbbell Front Raise", muscle: "shoulders", publicId: "Dumbbell_Front_Raise_t6zrnx" },
  { slug: "dumbbell-incline-hammer-press", name: "Dumbbell Incline Hammer Press", muscle: "shoulders", publicId: "Dumbbell_Incline_Hammer_Press_r1gzwx" },
  { slug: "dumbbell-incline-rear-lateral-raise", name: "Dumbbell Incline Rear Lateral Raise", muscle: "shoulders", publicId: "Dumbbell_Incline_Rear_Lateral_Raise_bgj6zd" },
  { slug: "dumbbell-iron-cross", name: "Dumbbell Iron Cross", muscle: "shoulders", publicId: "Dumbbell_Iron_Cross_ldyhza" },
  { slug: "dumbbell-lateral-raise", name: "Dumbbell Lateral Raise", muscle: "shoulders", publicId: "Dumbbell_Lateral_Raise_a51a6i" },
  { slug: "dumbbell-one-arm-lateral-raise", name: "Dumbbell One Arm Lateral Raise", muscle: "shoulders", publicId: "Dumbbell_One_Arm_Lateral_Raise_urfps3" },
  { slug: "dumbbell-rear-delt-row", name: "Dumbbell Rear Delt Row", muscle: "shoulders", publicId: "Dumbbell_Rear_Delt_Row_ngyf0r" },
  { slug: "dumbbell-rear-lateral-raise", name: "Dumbbell Rear Lateral Raise", muscle: "shoulders", publicId: "Dumbbell_Rear_Lateral_Raise_pmlmay" },
  { slug: "dumbbell-seated-front-raise", name: "Dumbbell Seated Front Raise", muscle: "shoulders", publicId: "Dumbbell_Seated_Front_Raise_m39lg8" },
  { slug: "dumbbell-seated-lateral-raise", name: "Dumbbell Seated Lateral Raise", muscle: "shoulders", publicId: "Dumbbell_Seated_Lateral_Raise_p2hq8a" },
  { slug: "dumbbell-upright-row", name: "Dumbbell Upright Row", muscle: "shoulders", publicId: "Dumbbell_Upright_Row_vngjhr" },
  { slug: "ez-barbell-anti-gravity-press", name: "EZ Barbell Anti Gravity Press", muscle: "shoulders", publicId: "EZ_Barbell_Anti_Gravity_Press_q2asyb" },
  { slug: "lever-lateral-raise", name: "Lever Lateral Raise", muscle: "shoulders", publicId: "Lever_Lateral_Raise_uwx3kn" },
  { slug: "lever-military-press", name: "Lever Military Press", muscle: "shoulders", publicId: "Lever_Military_Press_c5fel9" },
  { slug: "lever-seated-reverse-fly", name: "Lever Seated Reverse Fly", muscle: "shoulders", publicId: "Lever_Seated_Reverse_Fly_qourka" },
  { slug: "military-press", name: "Military Press", muscle: "shoulders", publicId: "Military_Press_dcskst" },
  { slug: "smith-seated-shoulder-press", name: "Smith Seated Shoulder Press", muscle: "shoulders", publicId: "Smith_Seated_Shoulder_Press_kway6x" },
  { slug: "stretching-band-warm-up-shoulder-stretch", name: "Stretching - Band Warm-up Shoulder Stretch", muscle: "shoulders", publicId: "Stretching_-_Band_Warm-up_Shoulder_Stretch_fo5qj7" },
  { slug: "stretching-rear-deltoid-stretch", name: "Stretching - Rear Deltoid Stretch", muscle: "shoulders", publicId: "Stretching_-_Rear_Deltoid_Stretch_tn18eg" },
  { slug: "stretching-seated-shoulder-flexor-depresor-retractor", name: "Stretching - Seated Shoulder Flexor Depresor Retractor", muscle: "shoulders", publicId: "Stretching_-_Seated_Shoulder_Flexor_Depresor_Retractor_gwknwi" },
  { slug: "barbell-rear-delt-raise", name: "Barbell Rear Delt Raise", muscle: "traps", publicId: "Barbell_Rear_Delt_Raise_gmrhs0" },
  { slug: "barbell-shrug", name: "Barbell Shrug", muscle: "traps", publicId: "Barbell_Shrug_c1shaw" },
  { slug: "dumbbell-incline-shrug", name: "Dumbbell Incline Shrug", muscle: "traps", publicId: "Dumbbell_Incline_Shrug_wnrdjn" },
  { slug: "dumbbell-shrug", name: "Dumbbell Shrug", muscle: "traps", publicId: "Dumbbell_Shrug_xdrfqr" },
  { slug: "lever-shrug", name: "Lever Shrug", muscle: "traps", publicId: "Lever_Shrug_qyvzgr" },
  { slug: "scapula-dips", name: "Scapula Dips", muscle: "traps", publicId: "Scapula_Dips_gotnus" },
  { slug: "stretching-neck-side-stretch", name: "Stretching - Neck Side Stretch", muscle: "traps", publicId: "Stretching_-_Neck_Side_Stretch_bmadwu" },
  { slug: "band-overhead-triceps-extension", name: "Band Overhead Triceps Extension", muscle: "triceps", publicId: "Band_Overhead_Triceps_Extension_j67lyp" },
  { slug: "band-side-triceps-pushdown", name: "Band Side Triceps Pushdown", muscle: "triceps", publicId: "Band_Side_Triceps_Pushdown_qvadr4" },
  { slug: "band-triceps-pushdown", name: "Band Triceps Pushdown", muscle: "triceps", publicId: "Band_Triceps_Pushdown_ggxzvc" },
  { slug: "barbell-close-grip-bench-press", name: "Barbell Close Grip Bench Press", muscle: "triceps", publicId: "Barbell_Close_Grip_Bench_Press_lquek0" },
  { slug: "bench-dips", name: "Bench Dips", muscle: "triceps", publicId: "Bench_Dips_nvwdfp" },
  { slug: "cable-lying-triceps-extension", name: "Cable Lying Triceps Extension", muscle: "triceps", publicId: "Cable_Lying_Triceps_Extension_tllxge" },
  { slug: "cable-overhead-triceps-extension-rope-attachment", name: "Cable Overhead Triceps Extension rope attachment", muscle: "triceps", publicId: "Cable_Overhead_Triceps_Extension_rope_attachment_ks6pyc" },
  { slug: "cable-pushdown-rope-attachment", name: "Cable Pushdown rope attachment", muscle: "triceps", publicId: "Cable_Pushdown_rope_attachment_crtr2r" },
  { slug: "cable-rope-high-pulley-overhead-triceps-extension", name: "Cable Rope High Pulley Overhead Triceps Extension", muscle: "triceps", publicId: "Cable_Rope_High_Pulley_Overhead_Triceps_Extension_vkwx3z" },
  { slug: "cable-standing-one-arm-triceps-extension", name: "Cable Standing One Arm Triceps Extension", muscle: "triceps", publicId: "Cable_Standing_One_Arm_Triceps_Extension_fpv6jf" },
  { slug: "cable-triceps-pushdown", name: "Cable Triceps Pushdown", muscle: "triceps", publicId: "Cable_Triceps_Pushdown_flqg74" },
  { slug: "close-grip-push-ups", name: "Close Grip Push-ups", muscle: "triceps", publicId: "Close_Grip_Push-ups_wvgnki" },
  { slug: "dumbbell-close-grip-press", name: "Dumbbell Close Grip Press", muscle: "triceps", publicId: "Dumbbell_Close_Grip_Press_hrxz6i" },
  { slug: "dumbbell-incline-triceps-extension", name: "Dumbbell Incline Triceps Extension", muscle: "triceps", publicId: "Dumbbell_Incline_Triceps_Extension_b7a9jj" },
  { slug: "dumbbell-kickback", name: "Dumbbell Kickback", muscle: "triceps", publicId: "Dumbbell_Kickback_k0gttw" },
  { slug: "dumbbell-lying-alternate-extension", name: "Dumbbell Lying Alternate Extension", muscle: "triceps", publicId: "Dumbbell_Lying_Alternate_Extension_a1whvf" },
  { slug: "dumbbell-lying-triceps-extension", name: "Dumbbell Lying Triceps Extension", muscle: "triceps", publicId: "Dumbbell_Lying_Triceps_Extension_vh9ftm" },
  { slug: "dumbbell-one-arm-triceps-extension", name: "Dumbbell One Arm Triceps Extension", muscle: "triceps", publicId: "Dumbbell_One_Arm_Triceps_Extension_qisjzv" },
  { slug: "dumbbell-pronate-grip-triceps-extension", name: "Dumbbell Pronate-grip Triceps Extension", muscle: "triceps", publicId: "Dumbbell_Pronate-grip_Triceps_Extension_gtosh5" },
  { slug: "dumbbell-seated-kickback", name: "Dumbbell Seated Kickback", muscle: "triceps", publicId: "Dumbbell_Seated_Kickback_m1axc1" },
  { slug: "dumbbell-seated-triceps-extension", name: "Dumbbell Seated Triceps Extension", muscle: "triceps", publicId: "Dumbbell_Seated_Triceps_Extension_bqh1wz" },
  { slug: "ez-barbell-lying-triceps-extension", name: "EZ Barbell Lying Triceps Extension", muscle: "triceps", publicId: "EZ_Barbell_Lying_Triceps_Extension_ceo4ur" },
  { slug: "lever-seated-dips", name: "Lever Seated Dips", muscle: "triceps", publicId: "Lever_Seated_Dips_q7pm6k" },
  { slug: "lever-triceps-extension", name: "Lever Triceps Extension", muscle: "triceps", publicId: "Lever_Triceps_Extension_m5rgk0" },
  { slug: "lever-triceps-extension-neutral-grip", name: "Lever Triceps Extension neutral grip", muscle: "triceps", publicId: "Lever_Triceps_Extension_neutral_grip_gevpog" },
  { slug: "old-school-reverse-extensions", name: "Old School Reverse Extensions", muscle: "triceps", publicId: "Old_School_Reverse_Extensions_mplwtl" },
  { slug: "stretching-kneeling-triceps-extension", name: "Stretching - Kneeling Triceps Extension", muscle: "triceps", publicId: "Stretching_-_Kneeling_Triceps_Extension_hu1ukv" },
  { slug: "stretching-reverse-dip", name: "Stretching - Reverse Dip", muscle: "triceps", publicId: "Stretching_-_Reverse_Dip_zugki6" },
]; 

export const EXERCISES_BY_MUSCLE = EXERCISE_LIBRARY.reduce<Record<string, ExerciseDemo[]>>(
  (acc, ex) => { (acc[ex.muscle] ??= []).push(ex); return acc; },
  {},
);
